name: Bau_De_Laplace
main: net23.net.baudelaplace.bau.Bau
version: 0.1.0
author: Vitor
website: baudelaplace.net23.net

commands:
  basic:
    aliases: "*"
    usage: "Uso: /<command> [param. de config.] ou /<command> [param.de config.] [novo valor]"
  getBau:
    usage: "Uso: /<command>"
  warp:
    description: "Cria, deleta ou transporta para posições fixas denominadas 'warp'"
    usage: "Uso: /<command> [nome_do_warp | set nome_do_warp | del nome_do_warp]"