name: Bau_De_Laplace
main: net23.net.baudelaplace.bau.Bau
version: 0.1.1
author: Vitor
website: baudelaplace.net23.net

commands:
  basic:
    aliases: "*"
    usage: "Uso: /<command> [param. de config.] ou /<command> [param.de config.] [novo valor]"
  getBau:
    usage: "Uso: /<command>"
  warp:
    description: "Cria, deleta ou transporta para posicoes fixas denominadas 'warp'"
    usage: "Uso: /<command> [nome_do_warp | set nome_do_warp | del nome_do_warp]"
    
permissions:
  getbau:
    default: op
    description: "Permissao para usar o comando getbau"
  healSign:
    default: op
    description: "Quem pode colocar Signs geradoras de vida infinita"